### PR TITLE
Bgm

### PR DESCRIPTION
**Pull request by timberwang0810**
Added three bgm tracks, and random shuffle play when each track ends

### CODE REVIEW

**Comment by austin-leung** [comment]
hm looks like u made the backend changes to reward in here too?

Do tracks only change when you switch tabs

**Review by austin-leung — APPROVED** [review]
I also noticed that there's bgm on the doing task screen, very nice!

Is there anything else I missed? Also can we change the coin under expected reward to like 24 instead of 24+?

**Comment by timberwang0810** [comment]
> hm looks like u made the backend changes to reward in here too?
> 
> Do tracks only change when you switch tabs

Not sure what u meant by track change. A sound is played when the tab is switched

**Comment by timberwang0810** [comment]
> I also noticed that there's bgm on the doing task screen, very nice!
> 
> Is there anything else I missed? Also can we change the coin under expected reward to like 24 instead of 24+?

I initially changed it but i added it back, b/c don't we have bonus reward now? So we can potentially get 24 + bonus

**Comment by austin-leung** [comment]
Also

> > hm looks like u made the backend changes to reward in here too?
> > Do tracks only change when you switch tabs
> 
> Not sure what u meant by track change. A sound is played when the tab is switched

o yea thats what i mean

For the bonus -- we should only show on-time bonus it's > 0 right? So they should just assume they don't get any bonus so no need for +.

**Comment by austin-leung** [comment]
Did you test it works as expected when the tracks loop all the way around? I haven't had time to wait to see if it works but I assume profh will not have time either /shrug

**Comment by timberwang0810** [comment]
> Also
> 
> > > hm looks like u made the backend changes to reward in here too?
> > > Do tracks only change when you switch tabs
> > 
> > 
> > Not sure what u meant by track change. A sound is played when the tab is switched
> 
> o yea thats what i mean
> 
> For the bonus -- we should only show on-time bonus it's > 0 right? So they should just assume they don't get any bonus so no need for +.

Yea that sounds good i'll add

**Comment by timberwang0810** [comment]
> Did you test it works as expected when the tracks loop all the way around? I haven't had time to wait to see if it works but I assume profh will not have time either /shrug



> Did you test it works as expected when the tracks loop all the way around? I haven't had time to wait to see if it works but I assume profh will not have time either /shrug

yea i tested it it should be fine

**Comment by austin-leung** [comment]
noice

**Pull request merged**
