### PR TITLE
Initialize task fields

### PR DESCRIPTION
**Pull request by austin-leung**
- Fix bug where you can create a task with duration 0 if you don't change anything
- Default duration to 20 minutes
- Show error message if you create a task without a name

When start now button is clicked without task name:
image

### CODE REVIEW

**Review by timberwang0810 — COMMENTED** [review]
Can probably add a red star near the text field signaling it's required

**Comment by austin-leung** [comment]
> Can probably add a red star near the text field signaling it's required

So always show the red star and then show the error message above when they submit without that field?

**Comment by timberwang0810** [comment]
> > Can probably add a red star near the text field signaling it's required
> 
> So always show the red star and then show the error message above when they submit without that field?

yea

**Comment by austin-leung** [comment]
image

**Review by timberwang0810 — APPROVED** [review]

**Pull request merged**
