### PR TITLE
Playground - Item menu scroll initial UI

### PR DESCRIPTION
**Pull request by austin-leung**
Just creating initial UI with horizontal scrolling and border.

image

Some todos with this - will fix later:
- Round item borders for first and last element
- Entire ScrollView is too far up. Will fix this when I add the box icon.
- Not sure if we want the ScrollView not having a right border until you scroll all the way to the right.

### CODE REVIEW

**Comment by austin-leung** [comment]
oops i didn't commit adding the painting and lamp to this pr -- will be in the next pr

**Review by timberwang0810 — COMMENTED** [review]
The top scroll is a bit too close to the top is there a way to move it down?

**Comment by austin-leung** [comment]
> The top scroll is a bit too close to the top is there a way to move it down?

yeah i talked about it in description but it will get moved down later when i add box icon and remove coin amount anyways

**Comment by timberwang0810** [comment]
> oops i didn't commit adding the painting and lamp to this pr -- will be in the next pr



> > The top scroll is a bit too close to the top is there a way to move it down?
> 
> yeah i talked about it in description but it will get moved down later when i add box icon and remove coin amount anyways

oops i didn't see that okay

**Review by timberwang0810 — APPROVED** [review]

**Pull request merged**
